# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prediction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2253, 912)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(460, 20, 715, 87))
        self.label.setStyleSheet("color: rgb(126, 2, 11);\n"
"font: 36pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(13, 278, 262, 48))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit1 = QtWidgets.QLineEdit(Form)
        self.lineEdit1.setGeometry(QtCore.QRect(284, 278, 380, 54))
        self.lineEdit1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit1.setObjectName("lineEdit1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(13, 341, 262, 48))
        self.label_3.setStyleSheet("\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(13, 404, 262, 48))
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(13, 467, 262, 48))
        self.label_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(13, 530, 262, 48))
        self.label_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(13, 593, 262, 48))
        self.label_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(13, 656, 262, 48))
        self.label_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(13, 719, 262, 48))
        self.label_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(856, 278, 262, 48))
        self.label_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(856, 341, 262, 48))
        self.label_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(856, 404, 262, 48))
        self.label_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(856, 467, 262, 48))
        self.label_15.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(856, 530, 262, 48))
        self.label_16.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(856, 593, 262, 48))
        self.label_17.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(856, 656, 262, 48))
        self.label_18.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(856, 719, 262, 48))
        self.label_19.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.lineEdit2 = QtWidgets.QLineEdit(Form)
        self.lineEdit2.setGeometry(QtCore.QRect(284, 341, 380, 54))
        self.lineEdit2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(Form)
        self.lineEdit3.setGeometry(QtCore.QRect(284, 404, 380, 54))
        self.lineEdit3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit4 = QtWidgets.QLineEdit(Form)
        self.lineEdit4.setGeometry(QtCore.QRect(284, 467, 380, 54))
        self.lineEdit4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit4.setObjectName("lineEdit4")
        self.lineEdit5 = QtWidgets.QLineEdit(Form)
        self.lineEdit5.setGeometry(QtCore.QRect(284, 530, 380, 54))
        self.lineEdit5.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit5.setObjectName("lineEdit5")
        self.lineEdit6 = QtWidgets.QLineEdit(Form)
        self.lineEdit6.setGeometry(QtCore.QRect(284, 593, 380, 54))
        self.lineEdit6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit6.setObjectName("lineEdit6")
        self.lineEdit11 = QtWidgets.QLineEdit(Form)
        self.lineEdit11.setGeometry(QtCore.QRect(1127, 278, 380, 54))
        self.lineEdit11.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit11.setObjectName("lineEdit11")
        self.lineEdit12 = QtWidgets.QLineEdit(Form)
        self.lineEdit12.setGeometry(QtCore.QRect(1127, 341, 380, 54))
        self.lineEdit12.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit12.setObjectName("lineEdit12")
        self.lineEdit13 = QtWidgets.QLineEdit(Form)
        self.lineEdit13.setGeometry(QtCore.QRect(1127, 404, 380, 54))
        self.lineEdit13.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit13.setObjectName("lineEdit13")
        self.lineEdit14 = QtWidgets.QLineEdit(Form)
        self.lineEdit14.setGeometry(QtCore.QRect(1127, 467, 380, 54))
        self.lineEdit14.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit14.setObjectName("lineEdit14")
        self.lineEdit15 = QtWidgets.QLineEdit(Form)
        self.lineEdit15.setGeometry(QtCore.QRect(1127, 530, 380, 54))
        self.lineEdit15.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit15.setObjectName("lineEdit15")
        self.lineEdit16 = QtWidgets.QLineEdit(Form)
        self.lineEdit16.setGeometry(QtCore.QRect(1127, 593, 380, 54))
        self.lineEdit16.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit16.setObjectName("lineEdit16")
        self.lineEdit17 = QtWidgets.QLineEdit(Form)
        self.lineEdit17.setGeometry(QtCore.QRect(1127, 656, 380, 54))
        self.lineEdit17.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit17.setObjectName("lineEdit17")
        self.lineEdit7 = QtWidgets.QLineEdit(Form)
        self.lineEdit7.setGeometry(QtCore.QRect(284, 656, 380, 54))
        self.lineEdit7.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit7.setObjectName("lineEdit7")
        self.lineEdit8 = QtWidgets.QLineEdit(Form)
        self.lineEdit8.setGeometry(QtCore.QRect(284, 719, 380, 54))
        self.lineEdit8.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit8.setObjectName("lineEdit8")
        self.lineEdit18 = QtWidgets.QLineEdit(Form)
        self.lineEdit18.setGeometry(QtCore.QRect(1127, 719, 380, 54))
        self.lineEdit18.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit18.setObjectName("lineEdit18")
        self.lineEdit9 = QtWidgets.QLineEdit(Form)
        self.lineEdit9.setGeometry(QtCore.QRect(284, 782, 380, 54))
        self.lineEdit9.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit9.setObjectName("lineEdit9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(13, 782, 262, 48))
        self.label_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(13, 845, 262, 48))
        self.label_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.lineEdit10 = QtWidgets.QLineEdit(Form)
        self.lineEdit10.setGeometry(QtCore.QRect(284, 845, 380, 54))
        self.lineEdit10.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit10.setObjectName("lineEdit10")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(856, 782, 262, 48))
        self.label_20.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(856, 845, 262, 48))
        self.label_21.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.lineEdit19 = QtWidgets.QLineEdit(Form)
        self.lineEdit19.setGeometry(QtCore.QRect(1127, 782, 380, 54))
        self.lineEdit19.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit19.setObjectName("lineEdit19")
        self.lineEdit20 = QtWidgets.QLineEdit(Form)
        self.lineEdit20.setGeometry(QtCore.QRect(1127, 845, 380, 54))
        self.lineEdit20.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit20.setObjectName("lineEdit20")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(1600, 170, 231, 61))
        self.label_22.setStyleSheet("\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(1600, 240, 271, 61))
        self.label_23.setStyleSheet("\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(1600, 320, 231, 61))
        self.label_24.setStyleSheet("\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(1600, 400, 311, 61))
        self.label_25.setStyleSheet("\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label_25.setObjectName("label_25")
        self.push = QtWidgets.QPushButton(Form)
        self.push.setGeometry(QtCore.QRect(1610, 570, 201, 91))
        self.push.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 17pt \"MS Shell Dlg 2\";")
        self.push.setObjectName("push")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(1560, 750, 171, 61))
        self.label_26.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.label_26.setObjectName("label_26")
        self.lineEdit21 = QtWidgets.QLabel(Form)
        self.lineEdit21.setGeometry(QtCore.QRect(1740, 750, 171, 61))
        self.lineEdit21.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 152, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit21.setObjectName("lineEdit21")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Mobile Price Prediction"))
        self.label_2.setText(_translate("Form", "Battery Power"))
        self.label_3.setText(_translate("Form", "Blue"))
        self.label_4.setText(_translate("Form", "Clock Speed"))
        self.label_5.setText(_translate("Form", "Dual Sim"))
        self.label_6.setText(_translate("Form", "FC"))
        self.label_7.setText(_translate("Form", "4 G"))
        self.label_8.setText(_translate("Form", "Int_Memory"))
        self.label_9.setText(_translate("Form", "M_Dep"))
        self.label_12.setText(_translate("Form", "PC"))
        self.label_13.setText(_translate("Form", "PX_Height"))
        self.label_14.setText(_translate("Form", "PX_Width"))
        self.label_15.setText(_translate("Form", "RAM"))
        self.label_16.setText(_translate("Form", "SC_H"))
        self.label_17.setText(_translate("Form", "SC_W"))
        self.label_18.setText(_translate("Form", "Talk_Time"))
        self.label_19.setText(_translate("Form", "3 G"))
        self.label_10.setText(_translate("Form", "Mobile_WT"))
        self.label_11.setText(_translate("Form", "N_Cores"))
        self.label_20.setText(_translate("Form", "Touch Screen"))
        self.label_21.setText(_translate("Form", "Wifi"))
        self.label_22.setText(_translate("Form", "0-Low Cost"))
        self.label_23.setText(_translate("Form", "1-Medium Cost"))
        self.label_24.setText(_translate("Form", "2-High Cost"))
        self.label_25.setText(_translate("Form", "3-Very High Cost"))
        self.push.setText(_translate("Form", "Predict"))
        self.label_26.setText(_translate("Form", "RESULT:"))
        self.lineEdit21.setText(_translate("Form", "Result Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
